- platform: mqtt
  name: "Temperature"
  state_topic: "sensor/temperature"
  unit_of_measurement: '°C'
- platform: mqtt
  name: "Humidity"
  expire_after: 0
  state_topic: "sensor/humidity"
  unit_of_measurement: '%'
- platform: mqtt
  name: "Airquality"
  expire_after: 0
  state_topic: "sensor/airquality"
  unit_of_measurement: "ppm"
- platform: mqtt
  name: "Delay time MQ135 DHT11"
  expire_after: 0
  state_topic: "setting/mq135dht11/return"
  unit_of_measurement: "s"
- platform: mqtt
  name: "Time send MQ135 DHT11"
  expire_after: 0
  state_topic: "sensor/timesend"
  
  
- platform: mqtt
  name: "Sensor door"
  expire_after: 960 # 16phut
  state_topic: "sensor/sensordoor"
  icon: mdi:home-lock
  
  
- platform: mqtt
  name: "Bell Mode"
  expire_after: 0
  state_topic: "control/doorbell/mode/return"
- platform: mqtt
  name: "Bell Time Run"
  expire_after: 0
  state_topic: "control/doorbell/time/return"
  unit_of_measurement: "s"
  icon: mdi:timer
- platform: mqtt
  name: "Bell State"
  expire_after: 0
  state_topic: "control/doorbell/return"
  icon: mdi:alarm-bell

- platform: time_date
  display_options:
    - 'time'

- platform: template
  sensors:
    time_open_door_sensor:
      friendly_name: "Time Door Open"
      value_template: '{% if is_state("sensor.sensor_door","Mở cửa") %} {{ relative_time(states.sensor.sensor_door.last_updated) }} {% endif %} {% if is_state("sensor.sensor_door","Đóng cửa") %} None {% endif %}'
      entity_id: sensor.time
